#!/bin/bash

set -e

env=${env:-$1}
if [[ -z $env ]]; then echo "Usage: $0 env"; exit 1; fi

echo -e "\033[34mBootstrapping Consul cluster...\033[0m"

source settings

for (( i=1; i<=$cluster_size; i++ )); do
  node=docker-swarm-${env}-$i
  echo "Running consul on $node..."
  node_ip=$(docker-machine ip $node)
  eval $(docker-machine env --shell bash $node)
  docker run -d --net=host --name consul --restart=unless-stopped \
         -e 'CONSUL_LOCAL_CONFIG={"skip_leave_on_interrupt": true}' \
         consul:v0.6.4 agent -server -dc aws-$region -ui -bind=$node_ip \
         -client=0.0.0.0 -bootstrap-expect=$cluster_size \
         $(if [[ $i -gt 1 ]]; then echo -retry-join=$(docker-machine ip docker-swarm-${env}-1); fi)
done
