#!/bin/bash

set -e

export env=$1

./provision-machines
./provision-consul-cluster
./configure-docker-cluster-for-consul
./provision-dnsmasq-forwarders
./provision-docker-swarm-managers
./provision-docker-swarm-nodes
./provision-overlay-network
./provision-rabbitmq-cluster

echo -e "\033[32mYour Docker Swarm, Consul, RabbitMQ cluster is ready:\033[0m"
docker-machine ls

machine_ip=$(docker-machine ip docker-swarm-${env}-1)
echo -e "\n\nRun \"docker -H tcp://${machine_ip}:4000 (command)\" to send commands to the Swarm cluster"
echo "Your Consul cluster admin UI is available at http://${machine_ip}:8500/"
echo "Your RabbitMQ cluster admin UI is available at http://${machine_ip}:15672/"
